User.create(name: "Sadaf", password:"1234")
User.create(name: "Garvin", password:"1234")
Book.create(name: "The Alchemist", cover_photo:"test.png", author:"THE Author", publisher:"One", publish_date:"2021-01-01")
Book.create(name: "The Magician", cover_photo:"test3.png", author:"THE Writer", publisher:"One", publish_date:"2021-01-01")
Book.create(name: "The Doctor", cover_photo:"test2.png", author:"THE Medic", publisher:"One", publish_date:"2021-01-01")
Reservation.create(date: "2000-10-19", due_date: "2000-10-29", city: "Caracas", user_id: 1)